#baseURL = "http://localhost:1313"
baseURL = "https://onesentforth.com/"
languageCode = "en-us"
title = "OneSentForth"
theme = "after-dark"
#metaDataFormat = "yaml"
#markup = "markdown"
#description needs to be 50-300 words. Get my description from discipleschool.com
googleAnalytics = "UA-68558525-2"
#disqusShortname = "onesentforth"
keywords = [
  "bible study",
  "disciple",
  "disciples",
  "discipleship",
  "disciple making",
  "church",
  "apologetics",
  "evangelism",
  "christianity",
  "jesus",
  "bible"
]

[params]
  author = "Jason West"
  description = "Hey, my name is Jason West. I create content and resources designed to help others become and produce true disciples of Jesus Christ. OnesentForth is my personal blog, which will serve as my outlet for sharing stuff with you."
  #images = [
  #  "https://source.unsplash.com/user/onesentforth/likes"
  #]

[social]
  facebook = "onesentforth"
  twitter = "onesentforth"

[params.seo.webmaster_verifications]
    google = "google33bb9c8df9b14443.html" # Optional, Google verification code
    bing = "D863718EBA7CEF2553A55CB4BFA1AC0B" # Optional, Bing verification code
    #alexa = "" # Optional, Alexa verification code
    yandex = "82aba20a16e81b5f" # Optional, Yandex verification code

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Posts"
  weight = 2
  identifier = "post"
  url = "/post/"
