#baseURL = "http://localhost:1313/"
baseURL = "https://discipleschool.com/"
languageCode = "en-us"
title = "Disciple School"
theme = "after-dark"
#markup = "markdown"
#description needs to be 50-300 words. Get my description from discipleschool.com
googleAnalytics = "UA-68558525-1"
#disqusShortname = ""
keywords = [
  "bible study",
  "discipling",
  "disciple",
  "disciple school",
  "discipleschool",
  "disciples",
  "discipleship",
  "disciple making",
  "making disciples",
  "true disciples",
  "church",
  "apologetics",
  "evangelism",
  "christianity",
  "jesus",
  "bible",
  "jason west",
  "apostolic",
  "pentecostal"
]

[blackfriday]
  hrefTargetBlank = true

[params]
  author = "Jason West"
  description = "Disciple School will help you become and produce true disciples of Jesus Christ."
  images = [
    "images/jason-red-tritone-16x9.jpg"
  ]

[social]
  facebook = "seeksavesend"
  twitter = "seeksavesend"

#[params.seo]
#  telegram_channel = "discipleschool" # omit the `@`

[params.seo.webmaster_verifications]
  google = "google33bb9c8df9b14443.html" # Optional, Google verification code
  bing = "EAD018090A1C80C7BCF1D0597504AFCE" # Optional, Bing verification code
  #alexa = "" # Optional, Alexa verification code
  yandex = "d211d986614bd557" # Optional, Yandex verification code

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS", "JSON"]

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Posts"
  weight = 2
  identifier = "post"
  url = "/post/"
[[menu.main]]
  name = "Search"
  weight = 3
  identifier = "search"
  url = "/search/"
