baseURL = "http://localhost:1313"
#baseURL = "https://discipleschool.com/"
languageCode = "en-us"
title = "Disciple School"
theme = "after-dark"
#metaDataFormat = "yaml"
#markup = "markdown"
#description needs to be 50-300 words. Get my description from discipleschool.com
googleAnalytics = "UA-68558525-1"
#disqusShortname = ""
keywords = [
  "bible study",
  "disciple",
  "disciples",
  "discipleship",
  "disciple making",
  "making disciples",
  "true disciples",
  "church",
  "apologetics",
  "evangelism",
  "christianity",
  "jesus",
  "bible",
  "jason west",
  "apostolic",
  "pentecostal"
]

[blackfriday]
  hrefTargetBlank = true

[params]
  author = "Jason West"
  description = "Hey, my name is Jason West. Disciple School is my platform for creating content and resources designed to help others become and produce true disciples of Jesus Christ."
  #images = [
  #  "https://source.unsplash.com/user/onesentforth/likes"
  #]

[social]
  facebook = "seeksavesend"
  twitter = "seeksavesend"

[params.seo.webmaster_verifications]
  #google = "google33bb9c8df9b14443.html" # Optional, Google verification code
  #bing = "D863718EBA7CEF2553A55CB4BFA1AC0B" # Optional, Bing verification code
  #alexa = "" # Optional, Alexa verification code
  #yandex = "82aba20a16e81b5f" # Optional, Yandex verification code

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS", "JSON"]

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Posts"
  weight = 2
  identifier = "post"
  url = "/post/"
[[menu.main]]
  name = "Search"
  weight = 3
  identifier = "search"
  url = "/search/"
